# Generated by Django 3.1.3 on 2020-11-18 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bonds', '0003_removed_uniqueness_check'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bond',
            options={'ordering': ('lei', 'created_date')},
        ),
        migrations.AddField(
            model_name='bond',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=True,
        ),
        migrations.AlterUniqueTogether(
            name='bond',
            unique_together={('lei', 'user')},
        ),
    ]
